spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/medisalud
    username: medisalud
    password: medisalud
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

logging:
  level:
    com.medisalud: DEBUG
    org.hibernate.SQL: DEBUG
